- alerts/google_home_api_break.markdown
This adds the following to the Google Home alert:
- More description
- A deprecation notice
- GitHub issue link
For a couple of weeks/months this integration was broken when Google changed the port they serve this information on, and to require a token header in the request.
> Adds more description, deprecation notice and GitHub link

- alerts/zwave_pi4_aeotec.markdown
As there's a known issue with the Aeotec stick and the Pi4, adding it here. This will impact every version of HA, but I've chosen 0.01 as a starting number.
> Add alert for Pi4 and the Aeotec stick

- src/layout/kb-detail.ts
`home-assistant.io/components/*` -> `home-assistant.io/integrations/*`
> Updates integration documentation links to new location

- alerts/tahoma
Somfy has blocked their unofficial API which now breaks this component. See https://github.com/home-assistant/home-assistant/issues/29744
> Tahoma alert

- src/layout/kb-detail.ts
- src/util/load_markdown.ts
Pulled out the Marked render option into `load_markdown`, so whenever used, it has consistent output ono the site.
The `tables` option has been removed (tables are enabled always, not configurable).
This allows for rebasing and merging #41, which is now blocked due to a build failure.
> Centralize Marked default options

- public/_headers
Sets the `Access-Control-Allow-Origin` header.
So we can make the alerts on our website work again...
> Add access control header

- alerts/automatic.markdown
This PR adds an alert re: Automatic's planned shutdown on 5/28/2020.
> Add alert about Automatic shutdown

- alerts/logi-circle.markdown
Adds an alert for Logi Circle to cover the fact they've temporarily suspended new API accounts. See [here](https://docs.google.com/forms/d/184FUILJ10rVxotyOQR5DAiu6GcCbK31AZszUdzT1ybs/closedform).
I'll set up a cron job to check that page or is this something we want to handle with a workflow on here?
> Add alert for logi-circle

- alerts/linky.markdown
To stop people [creating issue](https://github.com/home-assistant/core/issues?q=is%3Aissue+label%3A%22integration%3A+linky%22) and discuss on it [on the forum](https://community.home-assistant.io/t/can-not-log-with-linky/71163) and Discord.
WIP fix in : https://github.com/hacf-fr/home-assistant-core/tree/linky/new-api
> Add alert for Linky

- alerts/apple-betas-2020.markdown
This issue is thankfully resolved in iOS (and friends) beta 6. We are waiting to confirm that the WebKit fix is also included in the next Safari betas (I don't see any reason why it shouldn't be). In the mean time update this alert to reference the fix and also to remove the request to send feedback (no point spamming Apple now). Also updates the WebKit issue to the original from a dupe.
> Update Apple betas alert with details of fix in iOS14b6

- alerts/neato-vorwerk-vendor.markdown
We had a few users mention that Vorwerk is promoting a new app which migrates users account to a OAUTH model with 2FA.  The current integration does not support this and users have until March 2021 to migrate their account.  Setting up an alert letting them know not to do so until we fix things on the HA side otherwise they cannot use the integration.
https://github.com/home-assistant/core/issues/39378
https://github.com/home-assistant/core/issues/39165#issuecomment-680007713
> Add alert for vorwerk users on the neato integration

- alerts/tplink.markdown
As per [this tweet](https://twitter.com/TPLINKUK/status/1328687659133399043) TP-Link have removed their local API effectively killing Kasa products in Home Assistant. I've spent a little time looking but it seems there is no easily accessible release notes on TP-Link's website.
> Add TP-Link alert

- alerts/ziggo_mediabox_xl.markdown
Alerting users about the deprecation plans.
The documentation also warns people as per [this PR](https://github.com/home-assistant/home-assistant.io/pull/15743).
> Deprecating Ziggo Mediabox XL

- build-scripts/gulp/alerts.js
I noticed the RSS feed for the alerts site is not in the same order as the webpage. The events in the feed appear to be ordered alphabetically by entry ID rather then by publish date. This makes it difficult to use the RSS feed since external readers or feed watchers like the [feedreader](https://www.home-assistant.io/integrations/feedreader/) integration in Home Assistant generally expect RSS feeds to be in date order.
This PR fixes this by changing the script to sort the feed by `date_published` after it is created from the list of alerts in the folder.
Note that this is potentially a breaking change as it will change the order of the feed for existing watchers. I personally feel it is the right approach to make it easier to use going forward. Also existing automation for notifying …
> RSS feed in same order as site feed (by publish date)

- public/mobile.json
Implemented in home-assistant/iOS#1401 for iOS versions >= 2022.2 (11). This flag indicates that the alert should only be showed to the current user if they are an admin.
> Add "admin_only" flag to mobile alerts

- alerts/nello.markdown
According to https://analytics.home-assistant.io/#integrations, the Nello integration doesn't have a particularly large user base, so I could understand if that's too unimportant here.
> Add alert about Nello cloud API outage

- alerts/neato.markdown
It has come to our realization that new Neato devices no longer use the existing API so we need to notify users of such.
Fixes https://github.com/home-assistant/home-assistant.io/issues/20779
> Add alert for neato on unsupported botvacs

- alerts/zwavejs.markdown
Reference https://github.com/home-assistant/home-assistant.io/pull/21230. 700 series controllers presently have buggy firmware that causes the stick to become unresponsive. Essentially, it fails to send out Acks when it is receiving a lot of messages, which cause all of those devices to then begin flooding the controller with repeat messages, which makes the problem even worse as it cascades. We've reported this to SiLabs (from Z-Wave JS) weeks ago, but it doesn't seem like it'll be a quick fix. In the interim we should issue an alert (per @frenck).
> Add alert for 700 series Z-Wave controllers

- alerts/tplink.markdown
This alert creates confusion amongst potential users of Kasa devices. Clarify that the TP-Link alert only applies to certain UK-based plugs.
> Clarify alert

- alerts/twitch.markdown
Twitch is completely shutting down their v5 API on February 28, 2022. This is the API the current integration is based on. See: https://github.com/home-assistant/core/issues/54385
There is a workaround of a custom integration, but I didn't want to add it to the alert since it's not a HA supported item.
> Twitch API Shutdown Alert

- alerts/nest.markdown
Add alert for Nest Desktop Auth deprecation which has been deprecated and scheduled for shutdown in October.  Adding an alert based on discussion in https://github.com/home-assistant/home-assistant.io/pull/22610
Status: Issue https://github.com/home-assistant/core/issues/67662
Fixes issue https://github.com/home-assistant/home-assistant.io/issues/22141
> Add alert for Nest Desktop Auth deprecation

- alerts/logi_circle.markdown
Logitech have stopped accepting API applications for the Logi Circle API. This appears to be permanent.
> Add alert for Logi Circle

- alerts/nest.markdown
This change corrects some very minor typos in the Nest alert.
- Fixes typo in "October"
- Consistently formats the HA version `2022.6`
Didn't see anything else when proofreading.
> Fix: Correct typo and formatting in Nest alert

- build-scripts/gulp/alerts.js
- src/components/kb-display-version.ts
- src/components/kb-hass-version.ts
- src/data/alert.ts
~~Set to draft because this change will break clients relying on the min/max naming~~
Rename min/max to affected_from_version/resolved_in_version. Old properties are maintained for backwards compatibility.
> Rename min/max to introduced_in/resolved_in

- alerts/sochain.markdown
It no longer applies in Home Assistant 2022.8.0.
Marked as a draft until 2022.8 is shipped.
> Remove SoChain integration alert

- README.md
- build-scripts/gulp/alerts.js
Adds a new `"supervisor"` key to the generated alerts.json file.
example:
```json
"supervisor":{"package":"supervisor","affected_from_version":"2022.11.0","resolved_in_version":"2022.11.1"}
```
Core PR: https://github.com/home-assistant/core/pull/82862
> Add supervisor key to alerts.json

- utils/alert_as_json.js
Moves "file_slug" from extended to index JSON and renames to "id", there can not be 2 with the same file name so "id" is a good name.
> Move fileSlug as id to index json

- alerts/august.md
The August integration is about to break for anyone outside of North America who migrates their account to Yale Home (which is now being offered as of a few minutes/hours ago)
> Add Yale Home migration alert to august

- alerts/unifiprotect.md
Users are upgrading to Unifi Protect 3.x and finding it has backwards incompatible changes which break the integration.
> The latest firmware for Unifi Protect devices contains backward incompatible changes that are incompatible with older versions of Home Assistant. To avoid disruption, upgrade to Home Assistant 2024.3.2 or later before upgrading Unifi Protect to 3.x.
> Add Unifi Protect 3.x backward incompatible alert

- alerts/tesla_fleet.md
As discussed briefly on Discord, Tesla is going to start charging me personally for the use of every Home Assistant user with the previously built in Client ID. This was removed in 2025.1, but I know some people stayed on 2024.x so that they could keep using this credential.
I have raised a support request with Tesla to disable it before billing goes into effect on Febuary 1st.
I am more than happy for this alert to be reworded as much as required, and I know lots of people are struggling with the new configuration requirements, so I wanted to offer alternatives, which I also happen to be the Code Owner of.
Disclosure: I have a conflict of interest in that I personally own and operate Teslemetry.com
> Tesla Fleet built in credential is being removed

- alerts/yale.md
This PR adds an alert to notify users that they need to update to Home Assistant 2025.8.0 or later to continue using the Yale integration.
Home Assistant 2025.8.0 includes a critical fix that significantly reduces API traffic to Yale's servers. Without this update, older versions of Home Assistant will be rate limited or blocked by Yale's API, causing the integration to stop working.
- Added `alerts/yale.md` with a warning for users on versions below 2025.8.0
- Alert clearly indicates the integration "will stop working soon" to set proper expectations
Users running Home Assistant versions older than 2025.8.0 will see this alert and be prompted to update before their Yale integration stops functioning due to API restrictions.
> Add alert for Yale integration API changes requiring 2025.8.0+

- alerts/accuweather.md
Relates to https://github.com/home-assistant/core/issues/149554
All old API keys have expired, currently new keys are not compatible with the integration - a change to the backend library is required.
> Add alert for AccuWeather API change

- alerts/accuweather.md
Starting with HA 2025.9.2 the integration supports new API keys.
> Change Home Assistant version for AccuWeather alert
