- package.json
> knowledge -> alerts

- .devcontainer/devcontainer.json
- .vscode/tasks.json
- script/build
- script/develop
Nothing fancy, but a starting point.
I had to prefix the commands in the script files for them to be recognized inside the container.
If that breaks it for other setups I can look for another solution.
> Adds a simple devcontainer for local testing

- src/html/demo_alert_link.html.template
- src/html/index.html.template
- src/layout/kb-detail.ts
- src/layout/kb-layout.ts
- src/layout/kb-overview.ts
Quick refactor of the layout to be mobile first.
Also fixes vertical scrollbar caused by `100vh` on `<body>`.
- [Overview Small](https://i.imgur.com/zDD5uLA.png)
- [Overview Medium](https://i.imgur.com/DcfjJ4o.png)
- [Overview Large](https://i.imgur.com/ioOLK6N.png)
- [Detail Small](https://i.imgur.com/tubJoBB.png)
- [Detail Medium](https://i.imgur.com/o213sJN.png)
- [Detail Large](https://i.imgur.com/DdO6zvJ.png)
---
closes #9
> Mobile friendly UI

- build-scripts/gulp/alerts.js
- package.json
- script/build
- script/develop
- src/html/index.html.template
- yarn.lock
Closes https://github.com/home-assistant/alerts.home-assistant.io/issues/13
Closes https://github.com/home-assistant/alerts.home-assistant.io/issues/15
> Add RSS feed

- alerts/nederlandse_spoorwegen.markdown
Add alert about the Dutch railway integrations that is now broken duo the recent API changes
> 🚧 Add alert about NS API changes

- build-scripts/gulp/alerts.js
- public/_headers
Inspired by @frenck's https://github.com/home-assistant/home-assistant.io/blob/current/source/_headers
> Add caching headers

- alerts/adguard.markdown
Puts out an alert for the AdGuard integration breaking when using AdGuard Home v0.99.0
> Adds alert for adguard integration

- alerts/myq.markdown
This PR adds an alert about the `myq` integration breaking.
> Add alert for MyQ

- alerts/postnl.markdown
Create a PostNL alert as this component is currently broken in all versions of HA.
See issue https://github.com/home-assistant/home-assistant/issues/29002
> PostNL Alert

- alerts/myq.markdown
Adding details about MyQ being temporarily broken
> MyQ API change

- alerts/wwlln.markdown
This PR adds an alert regarding the removal of the WWLLN data source and integration.
> Add alert about WWLLN deprecation

- yarn.lock
Fix security warnings from Dependabot by upgrading packages.
> Fix security warnings

- alerts/wwlln.markdown
- alerts/zwave_pi4_aeotec.markdown
- src/layout/kb-detail.ts
- src/layout/kb-overview.ts
Hide integrations icons when they fail loading.
> Hide the icon on error

- alerts/toon.markdown
Adds an alert for Toon, until https://github.com/home-assistant/core/pull/36952 is merged and released.
> Add Toon alert

- alerts/loop_energy.markdown
I've created [an issue](https://github.com/home-assistant/home-assistant.io/issues/15345) for this, but someone on discord suggested I request an alert for it too.
> Loop energy integration will stop working.

- alerts/icloud.markdown
Related to this issue: https://github.com/home-assistant/core/issues/41315
> Add iCloud alert about sign-in notifications

- alerts/tplink.markdown
Updates the TP-Link alert with details of current work around
> Update TP Link alert for custom firmware option

- alerts/docker_2010.markdown
> Fix spelling

- alerts/homematicip_cloud.markdown
This has been reported many time in multiple community forms.
Also some EQ-3 employees have acknowledged these blocks.
> Add HomematicIP Cloud Alert

- alerts/security_bulletin.markdown
This is essentially a copy and paste of the blog post, probably a good idea to have an alert for this too.
> Add security alert

- public/mobile.json
Configuration for e.g. home-assistant/iOS#1376.
> Add mobile-specific alerts

- alerts/rituals_perfume_genie.markdown
Related issue: https://github.com/home-assistant/core/issues/47321
> Add alert for Rituals Perfume Genie

- alerts/simplisafe.markdown
This PR adds an alert regarding the SimpliSafe cloud API's recent and persistent flakiness. I am getting pings nearly every day across multiple channels (repos, forums, Reddit, email, etc.) and would like to release a common point of reference to which I may point people. Thanks!
> Add alert about SimpliSafe cloud API flakiness

- alerts/tplink.markdown
Just noticed that they are no longer offering the custom version since February so added an update to the alert. 
Not sure about the last sentence whether is appropriate.
> Update TP-Link alert for custom version unavailability

- alerts/bmw_connected_drive.markdown
As suggested by @dgomes in https://github.com/home-assistant/core/issues/53977.
FYI @gerard33.
> Add alert for BMW ConnectedDrive

- alerts/firefox.markdown
Create alert for Firefox not working with Ingress https://github.com/home-assistant/core/pull/55673
> Create Firefox alert

- alerts/hikvision.markdown
https://deploy-preview-409--home-assistant-alerts.netlify.app/#hikvision.markdown
> Add hikvision

- alerts/androidtv.markdown
Android TV 11 not supported by Android TV integration
https://github.com/JeffLIrion/python-androidtv/issues/271#issuecomment-925505211
https://github.com/home-assistant/core/issues/56567
> Android TV alert

- build-scripts/gulp/alerts.js
- package.json
- src/layout/kb-detail.ts
- src/util/load_markdown.ts
- yarn.lock
> Upgrade marked

- alerts/tuya.markdown
Put out an alert about the Tuya cloud API issues, affecting Home Assistant.
> Add Tuya sync delay alert

- alerts/samsung_internet.markdown
https://github.com/home-assistant/frontend/issues/11332
> Add Samsung alert

- README.md
- script/deploy
Deployments where moved to Netlify 2,5 years ago
Closes https://github.com/home-assistant/alerts.home-assistant.io/issues/25
> Remove old deploy script

- alerts/zwavejs.markdown
> Update zwavejs.markdown updating with fix available

- alerts/nest.markdown
Update the nest alert with the latest solution (using Web Auth and My Home Assistant) and future upgrade plans.
> Update the nest alert with the latest information

- alerts/nest.markdown
Update nest alert instructions for 2022.7 to point to new steps in documentation and interactive UI flow.
Related issues:
https://github.com/home-assistant/core/issues/74552
https://github.com/home-assistant/core/issues/67662
> Update nest alert instructions for 2022.7

- alerts/dark_sky.markdown
Update to the Dark Sky alert, making sure it contains the latest information.
> Update Dark Sky alert

- alerts/cloud.markdown
Add alert about the upcoming maintenance window
> Add cloud alert

- alerts/security-disclosure.md
- layouts/alert.html
Add alerts for Supervisor versions not updated (for whatever reason)
This PR awaits the public release of the blog post.
> Add Supervisor security disclosure alert

- alerts/ambiclimate.md
Sourced from https://www.ambiclimate.com/blogs/news/an-emotional-farewell-important-update-on-termination-of-ambi-climate-services
> Create ambiclimate alert

- alerts/aladdin_connect_2.md
> Update genie alert

- google_travel_time_picing_change.md
Fixes: #650
Link to documentation PR: https://github.com/home-assistant/home-assistant.io/pull/37165
> Add alert for google_travel_time free request reduction
